#!/usr/bin/env python
import rospy
from std_msgs.msg import Float32

def talker():
     pub = rospy.Publisher('chatter', Float32, queue_size = 100)
     rospy.init_node('talker', anonymous = True)
     number = 1
     while not rospy.is_shutdown():
         number +=1
         pub.publish(number)
         rospy.sleep(1)

if __name__ == '__main__':
     try: 
         talker()
     except rospy.ROSInterruptException:
         pass
