#!/usr/bin/env python

import rospy
from std_msgs.msg import Float32

def callback(data):
     rospy.loginfo(' I heard %s', data.data)

def listener():
     rospy.init_node('listener', anonymous = True)
     rospy.Subscriber('chatter', Float32, callback)
     rospy.spin()

if __name__ == '__main__':
    listener()
    rospy.sleep(5)

